# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OnDx1-vOsB2Lzma3aP8XzTdThE6Uv5es
"""

from flask import Flask, render_template, request, redirect, url_for
from flask_sqlalchemy import SQLAlchemy

app = Flask(__name__)

# Configuração do banco de dados
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///entidades.db'
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
db = SQLAlchemy(app)

# Modelo Entidade
class Entidade(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    nome = db.Column(db.String(100), nullable=False)
    categoria = db.Column(db.String(50), nullable=False)
    descricao = db.Column(db.String(200), nullable=False)
    instagram = db.Column(db.String(150), nullable=True)  # Novo campo

    def __repr__(self):
        return f"<Entidade {self.nome}>"

# Inicializa o banco com algumas entidades se ele estiver vazio
@app.before_request
def cria_banco():
    db.create_all()
    if Entidade.query.count() == 0:
        exemplos = [
            Entidade(
                nome="Atlética UFABC",
                categoria="Esportes",
                descricao="Coordena esportes e integração.",
                instagram="https://instagram.com/atletica.ufabc"
            ),
            Entidade(
                nome="Banda Experimental UFABC",
                categoria="Cultura",
                descricao="Grupo musical com ensaios e shows.",
                instagram="https://instagram.com/banda.experimental.ufabc"
            ),
            Entidade(
                nome="UFABC Rocket Design",
                categoria="Técnica",
                descricao="Equipe de foguetes experimentais.",
                instagram="https://instagram.com/ufabc.rocket"
            ),
            Entidade(
                nome="PET Computação UFABC",
                categoria="Acadêmica",
                descricao="Programa de Educação Tutorial em Computação.",
                instagram="https://instagram.com/petcomputacaoufabc"
            ),
            Entidade(
                nome="DCE Livre da UFABC",
                categoria="Política",
                descricao="Representação política dos estudantes.",
                instagram="https://instagram.com/dcelivre.ufabc"
            )
        ]
        db.session.add_all(exemplos)
        db.session.commit()

# Rotas
@app.route('/')
def index():
    return render_template('index.html')

@app.route('/formulario', methods=['GET', 'POST'])
def formulario():
    if request.method == 'POST':
        dados = {
            "curso": request.form['curso'],
            "periodo": request.form['periodo'],
            "tipo": request.form['tipo'],
            "formatoAtividade": request.form['formatoAtividade'],
            "modalidadeAtividade": request.form['modalidadeAtividade']
        }
        return redirect(url_for('resultado', **dados))
    return render_template('form.html')

@app.route('/resultado')
def resultado():
    tipo = request.args.get('tipo')
    formatoAtividade = request.args.get('formatoAtividade')
    modalidadeAtividade = request.args.get('modalidadeAtividade')

    entidades = Entidade.query.all()
    afinidade = []

    for e in entidades:
        score = 0

        # Categoria principal
        if e.categoria.lower() == tipo.lower():
            score += 7

        # Preferência social
        if formatoAtividade == "FORMA_GRU" and e.categoria in ["Esportes", "Cultura", "Política"]:
            score += 3
        if formatoAtividade == "FORMA_IND" and e.categoria in ["Técnica", "Acadêmica"]:
            score += 3

        # Preferência prática/teórica
        if modalidadeAtividade == "ATIV_PRA" and e.categoria in ["Esportes", "Técnica"]:
            score += 3
        if modalidadeAtividade == "ATIV_TEO" and e.categoria in ["Acadêmica", "Política"]:
            score += 3

        # Bônus se descrição tiver alguma palavra-chave
        descricao_lower = e.descricao.lower()
        if "integração" in descricao_lower or "equipe" in descricao_lower:
            score += 2

        afinidade.append((score, e))

    afinidade.sort(reverse=True, key=lambda x: x[0])
    recomendadas = [ (e, score) for score, e in afinidade if score > 0 ]

    return render_template('result.html', entidades=recomendadas)


@app.route('/cadastrar', methods=['GET', 'POST'])
def cadastrar():
    if request.method == 'POST':
        nome = request.form['nome']
        categoria = request.form['categoria']
        descricao = request.form['descricao']
        instagram = request.form['instagram']
        nova = Entidade(nome=nome, categoria=categoria, descricao=descricao, instagram=instagram)
        db.session.add(nova)
        db.session.commit()
        return redirect(url_for('index'))
    return render_template('cadastro.html')


if __name__ == '__main__':
    app.run(debug=True)